#+title: Things2Org

The (eventual) aim of this software is to provide bidirectional sync of Things.app and org-mode files.

To do this, it makes use of Things Cloud.

* Install

#+begin_src sh
bundle # installs the Ruby gems
#+end_src

* Running it

** Fetch your data

You will need to make your =history_key= available for this.

#+begin_src sh
history_key="[...]" ./fetch_all_history.fish
#+end_src

This will generate a bunch of =items.*.json= files with all your data.

** Print your inbox

#+begin_src sh
./make_inbox.rb > inbox.org
#+end_src

This will print your Things inbox as an org mode file.

** List your extra files

#+begin_src sh
./list_extra_files.rb
#+end_src

The assumption of this software is that each area and each project will be contained in its own file. This script prints the file structure of these areas and projects.

The names of the areas and projects will be normalized, so "My Project" will become "my-project.org".

** Make your extra files

#+begin_src sh
./make_extra_file.rb my-project.org > my-project.org
#+end_src

This will print the contents of the project named "My Project" and store it in =my-project.org=.
